/* 
 * Xpertdoc SmartFlows
 *
 * This describes the REST api for one Xpertdoc SmartFlows project
 *
 * OpenAPI spec version: 4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Xpertdoc.SmartFlows.Client.Client.SwaggerDateConverter;

namespace Xpertdoc.SmartFlows.Client.Model
{
    /// <summary>
    /// GcpVendorCapability
    /// </summary>
    [DataContract]
    public partial class GcpVendorCapability :  IEquatable<GcpVendorCapability>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum Range for "range"
            /// </summary>
            [EnumMember(Value = "range")]
            Range,
            
            /// <summary>
            /// Enum Select for "select"
            /// </summary>
            [EnumMember(Value = "select")]
            Select,
            
            /// <summary>
            /// Enum TypedValue for "typedValue"
            /// </summary>
            [EnumMember(Value = "typedValue")]
            TypedValue
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GcpVendorCapability" /> class.
        /// </summary>
        /// <param name="Type">Type.</param>
        /// <param name="Id">Id.</param>
        /// <param name="DisplayName">DisplayName.</param>
        /// <param name="Range">Range.</param>
        /// <param name="Select">Select.</param>
        /// <param name="TypedValue">TypedValue.</param>
        public GcpVendorCapability(TypeEnum? Type = default(TypeEnum?), string Id = default(string), string DisplayName = default(string), GcpVendorCapabilityRange Range = default(GcpVendorCapabilityRange), List<GcpVendorCapabilitySelect> Select = default(List<GcpVendorCapabilitySelect>), GcpVendorCapabilityTypedValue TypedValue = default(GcpVendorCapabilityTypedValue))
        {
            this.Type = Type;
            this.Id = Id;
            this.DisplayName = DisplayName;
            this.Range = Range;
            this.Select = Select;
            this.TypedValue = TypedValue;
        }
        

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets DisplayName
        /// </summary>
        [DataMember(Name="displayName", EmitDefaultValue=false)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or Sets Range
        /// </summary>
        [DataMember(Name="range", EmitDefaultValue=false)]
        public GcpVendorCapabilityRange Range { get; set; }

        /// <summary>
        /// Gets or Sets Select
        /// </summary>
        [DataMember(Name="select", EmitDefaultValue=false)]
        public List<GcpVendorCapabilitySelect> Select { get; set; }

        /// <summary>
        /// Gets or Sets TypedValue
        /// </summary>
        [DataMember(Name="typedValue", EmitDefaultValue=false)]
        public GcpVendorCapabilityTypedValue TypedValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GcpVendorCapability {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Range: ").Append(Range).Append("\n");
            sb.Append("  Select: ").Append(Select).Append("\n");
            sb.Append("  TypedValue: ").Append(TypedValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as GcpVendorCapability);
        }

        /// <summary>
        /// Returns true if GcpVendorCapability instances are equal
        /// </summary>
        /// <param name="other">Instance of GcpVendorCapability to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GcpVendorCapability other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Type == other.Type ||
                    this.Type != null &&
                    this.Type.Equals(other.Type)
                ) && 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.DisplayName == other.DisplayName ||
                    this.DisplayName != null &&
                    this.DisplayName.Equals(other.DisplayName)
                ) && 
                (
                    this.Range == other.Range ||
                    this.Range != null &&
                    this.Range.Equals(other.Range)
                ) && 
                (
                    this.Select == other.Select ||
                    this.Select != null &&
                    this.Select.SequenceEqual(other.Select)
                ) && 
                (
                    this.TypedValue == other.TypedValue ||
                    this.TypedValue != null &&
                    this.TypedValue.Equals(other.TypedValue)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Type != null)
                    hash = hash * 59 + this.Type.GetHashCode();
                if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                if (this.DisplayName != null)
                    hash = hash * 59 + this.DisplayName.GetHashCode();
                if (this.Range != null)
                    hash = hash * 59 + this.Range.GetHashCode();
                if (this.Select != null)
                    hash = hash * 59 + this.Select.GetHashCode();
                if (this.TypedValue != null)
                    hash = hash * 59 + this.TypedValue.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
