/*
 * Xpertdoc SmartFlows
 * This describes the REST api for one Xpertdoc SmartFlows project
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package xpertdoc.smartflows.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.Objects;

/**
 * CustomContentField
 */
@javax.annotation.Generated(value = "xpertdoc.smartflows.codegen.languages.JavaClientCodegen", date = "2018-05-22T10:07:28.195+02:00")
public class CustomContentField {
  @SerializedName("id")
  private String id = null;

  @SerializedName("displayName")
  private String displayName = null;

  @SerializedName("fieldName")
  private String fieldName = null;

  @SerializedName("description")
  private String description = null;

  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    TEXT("text"),
    
    MULTILINETEXT("multiLineText"),
    
    RICHTEXT("richText"),
    
    NUMBER("number"),
    
    BOOLEAN("boolean"),
    
    ENTITYREF("entityRef"),
    
    DATA("data"),
    
    DATE("date"),
    
    TIME("time"),
    
    DATETIME("dateTime"),
    
    OPTIONSET("optionset");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  @SerializedName("required")
  private Boolean required = false;

  @SerializedName("repeating")
  private Boolean repeating = false;

  @SerializedName("text")
  private CustomContentFieldText text = null;

  @SerializedName("multiLineText")
  private CustomContentFieldText multiLineText = null;

  @SerializedName("richText")
  private CustomContentFieldText richText = null;

  @SerializedName("optionset")
  private CustomContentFieldOptionset optionset = null;

  @SerializedName("number")
  private CustomContentFieldNumber number = null;

  @SerializedName("boolean")
  private CustomContentFieldBoolean _boolean = null;

  @SerializedName("entityRef")
  private CustomContentFieldEntityRef entityRef = null;

  @SerializedName("data")
  private CustomContentFieldData data = null;

  @SerializedName("date")
  private CustomContentFieldDate date = null;

  @SerializedName("time")
  private CustomContentFieldTime time = null;

  @SerializedName("dateTime")
  private CustomContentFieldDateTime dateTime = null;

  public CustomContentField id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CustomContentField displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @ApiModelProperty(value = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public CustomContentField fieldName(String fieldName) {
    this.fieldName = fieldName;
    return this;
  }

   /**
   * Get fieldName
   * @return fieldName
  **/
  @ApiModelProperty(value = "")
  public String getFieldName() {
    return fieldName;
  }

  public void setFieldName(String fieldName) {
    this.fieldName = fieldName;
  }

  public CustomContentField description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CustomContentField type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public CustomContentField required(Boolean required) {
    this.required = required;
    return this;
  }

   /**
   * Get required
   * @return required
  **/
  @ApiModelProperty(value = "")
  public Boolean isRequired() {
    return required;
  }

  public void setRequired(Boolean required) {
    this.required = required;
  }

  public CustomContentField repeating(Boolean repeating) {
    this.repeating = repeating;
    return this;
  }

   /**
   * Get repeating
   * @return repeating
  **/
  @ApiModelProperty(value = "")
  public Boolean isRepeating() {
    return repeating;
  }

  public void setRepeating(Boolean repeating) {
    this.repeating = repeating;
  }

  public CustomContentField text(CustomContentFieldText text) {
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  @ApiModelProperty(value = "")
  public CustomContentFieldText getText() {
    return text;
  }

  public void setText(CustomContentFieldText text) {
    this.text = text;
  }

  public CustomContentField multiLineText(CustomContentFieldText multiLineText) {
    this.multiLineText = multiLineText;
    return this;
  }

   /**
   * Get multiLineText
   * @return multiLineText
  **/
  @ApiModelProperty(value = "")
  public CustomContentFieldText getMultiLineText() {
    return multiLineText;
  }

  public void setMultiLineText(CustomContentFieldText multiLineText) {
    this.multiLineText = multiLineText;
  }

  public CustomContentField richText(CustomContentFieldText richText) {
    this.richText = richText;
    return this;
  }

   /**
   * Get richText
   * @return richText
  **/
  @ApiModelProperty(value = "")
  public CustomContentFieldText getRichText() {
    return richText;
  }

  public void setRichText(CustomContentFieldText richText) {
    this.richText = richText;
  }

  public CustomContentField optionset(CustomContentFieldOptionset optionset) {
    this.optionset = optionset;
    return this;
  }

   /**
   * Get optionset
   * @return optionset
  **/
  @ApiModelProperty(value = "")
  public CustomContentFieldOptionset getOptionset() {
    return optionset;
  }

  public void setOptionset(CustomContentFieldOptionset optionset) {
    this.optionset = optionset;
  }

  public CustomContentField number(CustomContentFieldNumber number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  @ApiModelProperty(value = "")
  public CustomContentFieldNumber getNumber() {
    return number;
  }

  public void setNumber(CustomContentFieldNumber number) {
    this.number = number;
  }

  public CustomContentField _boolean(CustomContentFieldBoolean _boolean) {
    this._boolean = _boolean;
    return this;
  }

   /**
   * Get _boolean
   * @return _boolean
  **/
  @ApiModelProperty(value = "")
  public CustomContentFieldBoolean getBoolean() {
    return _boolean;
  }

  public void setBoolean(CustomContentFieldBoolean _boolean) {
    this._boolean = _boolean;
  }

  public CustomContentField entityRef(CustomContentFieldEntityRef entityRef) {
    this.entityRef = entityRef;
    return this;
  }

   /**
   * Get entityRef
   * @return entityRef
  **/
  @ApiModelProperty(value = "")
  public CustomContentFieldEntityRef getEntityRef() {
    return entityRef;
  }

  public void setEntityRef(CustomContentFieldEntityRef entityRef) {
    this.entityRef = entityRef;
  }

  public CustomContentField data(CustomContentFieldData data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(value = "")
  public CustomContentFieldData getData() {
    return data;
  }

  public void setData(CustomContentFieldData data) {
    this.data = data;
  }

  public CustomContentField date(CustomContentFieldDate date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(value = "")
  public CustomContentFieldDate getDate() {
    return date;
  }

  public void setDate(CustomContentFieldDate date) {
    this.date = date;
  }

  public CustomContentField time(CustomContentFieldTime time) {
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @ApiModelProperty(value = "")
  public CustomContentFieldTime getTime() {
    return time;
  }

  public void setTime(CustomContentFieldTime time) {
    this.time = time;
  }

  public CustomContentField dateTime(CustomContentFieldDateTime dateTime) {
    this.dateTime = dateTime;
    return this;
  }

   /**
   * Get dateTime
   * @return dateTime
  **/
  @ApiModelProperty(value = "")
  public CustomContentFieldDateTime getDateTime() {
    return dateTime;
  }

  public void setDateTime(CustomContentFieldDateTime dateTime) {
    this.dateTime = dateTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomContentField customContentField = (CustomContentField) o;
    return Objects.equals(this.id, customContentField.id) &&
        Objects.equals(this.displayName, customContentField.displayName) &&
        Objects.equals(this.fieldName, customContentField.fieldName) &&
        Objects.equals(this.description, customContentField.description) &&
        Objects.equals(this.type, customContentField.type) &&
        Objects.equals(this.required, customContentField.required) &&
        Objects.equals(this.repeating, customContentField.repeating) &&
        Objects.equals(this.text, customContentField.text) &&
        Objects.equals(this.multiLineText, customContentField.multiLineText) &&
        Objects.equals(this.richText, customContentField.richText) &&
        Objects.equals(this.optionset, customContentField.optionset) &&
        Objects.equals(this.number, customContentField.number) &&
        Objects.equals(this._boolean, customContentField._boolean) &&
        Objects.equals(this.entityRef, customContentField.entityRef) &&
        Objects.equals(this.data, customContentField.data) &&
        Objects.equals(this.date, customContentField.date) &&
        Objects.equals(this.time, customContentField.time) &&
        Objects.equals(this.dateTime, customContentField.dateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, displayName, fieldName, description, type, required, repeating, text, multiLineText, richText, optionset, number, _boolean, entityRef, data, date, time, dateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomContentField {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    fieldName: ").append(toIndentedString(fieldName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("    repeating: ").append(toIndentedString(repeating)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    multiLineText: ").append(toIndentedString(multiLineText)).append("\n");
    sb.append("    richText: ").append(toIndentedString(richText)).append("\n");
    sb.append("    optionset: ").append(toIndentedString(optionset)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    _boolean: ").append(toIndentedString(_boolean)).append("\n");
    sb.append("    entityRef: ").append(toIndentedString(entityRef)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    dateTime: ").append(toIndentedString(dateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

