/*
 * Xpertdoc SmartFlows
 * This describes the REST api for one Xpertdoc SmartFlows project
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package xpertdoc.smartflows.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * DocGenSettingsResultChartData
 */
@javax.annotation.Generated(value = "xpertdoc.smartflows.codegen.languages.JavaClientCodegen", date = "2018-05-22T10:07:28.195+02:00")
public class DocGenSettingsResultChartData {
  @SerializedName("include")
  private Boolean include = false;

  @SerializedName("instructionId")
  private String instructionId = null;

  public DocGenSettingsResultChartData include(Boolean include) {
    this.include = include;
    return this;
  }

   /**
   * Get include
   * @return include
  **/
  @ApiModelProperty(value = "")
  public Boolean isInclude() {
    return include;
  }

  public void setInclude(Boolean include) {
    this.include = include;
  }

  public DocGenSettingsResultChartData instructionId(String instructionId) {
    this.instructionId = instructionId;
    return this;
  }

   /**
   * Get instructionId
   * @return instructionId
  **/
  @ApiModelProperty(value = "")
  public String getInstructionId() {
    return instructionId;
  }

  public void setInstructionId(String instructionId) {
    this.instructionId = instructionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocGenSettingsResultChartData docGenSettingsResultChartData = (DocGenSettingsResultChartData) o;
    return Objects.equals(this.include, docGenSettingsResultChartData.include) &&
        Objects.equals(this.instructionId, docGenSettingsResultChartData.instructionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(include, instructionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocGenSettingsResultChartData {\n");
    
    sb.append("    include: ").append(toIndentedString(include)).append("\n");
    sb.append("    instructionId: ").append(toIndentedString(instructionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

