/*
 * Xpertdoc SmartFlows
 * This describes the REST api for one Xpertdoc SmartFlows project
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package xpertdoc.smartflows.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Gets or Sets flowExecutionStatus
 */
@JsonAdapter(FlowExecutionStatus.Adapter.class)
public enum FlowExecutionStatus {
  
  QUEUED("Queued"),
  
  RUNNING("Running"),
  
  WAITING("Waiting"),
  
  USERINPUT("UserInput"),
  
  SUCCESS("Success"),
  
  ERROR("Error"),
  
  CANCELED("Canceled"),
  
  SELECTFLOW("SelectFlow"),
  
  INTERRUPTED("Interrupted");

  private String value;

  FlowExecutionStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static FlowExecutionStatus fromValue(String text) {
    for (FlowExecutionStatus b : FlowExecutionStatus.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<FlowExecutionStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final FlowExecutionStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public FlowExecutionStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return FlowExecutionStatus.fromValue(String.valueOf(value));
    }
  }
}

