/*
 * Xpertdoc SmartFlows
 * This describes the REST api for one Xpertdoc SmartFlows project
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package xpertdoc.smartflows.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * GeneratedDocument
 */
@javax.annotation.Generated(value = "xpertdoc.smartflows.codegen.languages.JavaClientCodegen", date = "2018-05-22T10:07:28.195+02:00")
public class GeneratedDocument {
  @SerializedName("displayName")
  private String displayName = null;

  @SerializedName("createdAt")
  private String createdAt = null;

  @SerializedName("createdBy")
  private IdWithName createdBy = null;

  @SerializedName("properties")
  private GeneratedDocumentProperties properties = null;

  @SerializedName("content")
  private GeneratedDocumentContent content = null;

  @SerializedName("pages")
  private List<GeneratedDocumentPages> pages = null;

  @SerializedName("charts")
  private List<GeneratedDocumentCharts> charts = null;

  @SerializedName("messages")
  private List<StatusMessage> messages = null;

  public GeneratedDocument displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @ApiModelProperty(value = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public GeneratedDocument createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public GeneratedDocument createdBy(IdWithName createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(value = "")
  public IdWithName getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(IdWithName createdBy) {
    this.createdBy = createdBy;
  }

  public GeneratedDocument properties(GeneratedDocumentProperties properties) {
    this.properties = properties;
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @ApiModelProperty(value = "")
  public GeneratedDocumentProperties getProperties() {
    return properties;
  }

  public void setProperties(GeneratedDocumentProperties properties) {
    this.properties = properties;
  }

  public GeneratedDocument content(GeneratedDocumentContent content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @ApiModelProperty(value = "")
  public GeneratedDocumentContent getContent() {
    return content;
  }

  public void setContent(GeneratedDocumentContent content) {
    this.content = content;
  }

  public GeneratedDocument pages(List<GeneratedDocumentPages> pages) {
    this.pages = pages;
    return this;
  }

  public GeneratedDocument addPagesItem(GeneratedDocumentPages pagesItem) {
    if (this.pages == null) {
      this.pages = new ArrayList<GeneratedDocumentPages>();
    }
    this.pages.add(pagesItem);
    return this;
  }

   /**
   * Get pages
   * @return pages
  **/
  @ApiModelProperty(value = "")
  public List<GeneratedDocumentPages> getPages() {
    return pages;
  }

  public void setPages(List<GeneratedDocumentPages> pages) {
    this.pages = pages;
  }

  public GeneratedDocument charts(List<GeneratedDocumentCharts> charts) {
    this.charts = charts;
    return this;
  }

  public GeneratedDocument addChartsItem(GeneratedDocumentCharts chartsItem) {
    if (this.charts == null) {
      this.charts = new ArrayList<GeneratedDocumentCharts>();
    }
    this.charts.add(chartsItem);
    return this;
  }

   /**
   * Get charts
   * @return charts
  **/
  @ApiModelProperty(value = "")
  public List<GeneratedDocumentCharts> getCharts() {
    return charts;
  }

  public void setCharts(List<GeneratedDocumentCharts> charts) {
    this.charts = charts;
  }

  public GeneratedDocument messages(List<StatusMessage> messages) {
    this.messages = messages;
    return this;
  }

  public GeneratedDocument addMessagesItem(StatusMessage messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<StatusMessage>();
    }
    this.messages.add(messagesItem);
    return this;
  }

   /**
   * Get messages
   * @return messages
  **/
  @ApiModelProperty(value = "")
  public List<StatusMessage> getMessages() {
    return messages;
  }

  public void setMessages(List<StatusMessage> messages) {
    this.messages = messages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeneratedDocument generatedDocument = (GeneratedDocument) o;
    return Objects.equals(this.displayName, generatedDocument.displayName) &&
        Objects.equals(this.createdAt, generatedDocument.createdAt) &&
        Objects.equals(this.createdBy, generatedDocument.createdBy) &&
        Objects.equals(this.properties, generatedDocument.properties) &&
        Objects.equals(this.content, generatedDocument.content) &&
        Objects.equals(this.pages, generatedDocument.pages) &&
        Objects.equals(this.charts, generatedDocument.charts) &&
        Objects.equals(this.messages, generatedDocument.messages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayName, createdAt, createdBy, properties, content, pages, charts, messages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeneratedDocument {\n");
    
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    pages: ").append(toIndentedString(pages)).append("\n");
    sb.append("    charts: ").append(toIndentedString(charts)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

