/* 
 * SmartFlows
 *
 * This describes the REST api for one SmartFlows project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Xpertdoc.SmartFlows.Client.SwaggerDateConverter;

namespace Xpertdoc.SmartFlows.Model
{
    /// <summary>
    /// FlowSettings
    /// </summary>
    [DataContract]
    public partial class FlowSettings :  IEquatable<FlowSettings>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FlowSettings" /> class.
        /// </summary>
        /// <param name="GroupToSingleDocument">GroupToSingleDocument.</param>
        /// <param name="AskQuestionsFirst">AskQuestionsFirst.</param>
        public FlowSettings(bool? GroupToSingleDocument = default(bool?), bool? AskQuestionsFirst = default(bool?))
        {
            this.GroupToSingleDocument = GroupToSingleDocument;
            this.AskQuestionsFirst = AskQuestionsFirst;
        }
        
        /// <summary>
        /// Gets or Sets GroupToSingleDocument
        /// </summary>
        [DataMember(Name="groupToSingleDocument", EmitDefaultValue=false)]
        public bool? GroupToSingleDocument { get; set; }

        /// <summary>
        /// Gets or Sets AskQuestionsFirst
        /// </summary>
        [DataMember(Name="askQuestionsFirst", EmitDefaultValue=false)]
        public bool? AskQuestionsFirst { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FlowSettings {\n");
            sb.Append("  GroupToSingleDocument: ").Append(GroupToSingleDocument).Append("\n");
            sb.Append("  AskQuestionsFirst: ").Append(AskQuestionsFirst).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FlowSettings);
        }

        /// <summary>
        /// Returns true if FlowSettings instances are equal
        /// </summary>
        /// <param name="input">Instance of FlowSettings to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FlowSettings input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.GroupToSingleDocument == input.GroupToSingleDocument ||
                    (this.GroupToSingleDocument != null &&
                    this.GroupToSingleDocument.Equals(input.GroupToSingleDocument))
                ) && 
                (
                    this.AskQuestionsFirst == input.AskQuestionsFirst ||
                    (this.AskQuestionsFirst != null &&
                    this.AskQuestionsFirst.Equals(input.AskQuestionsFirst))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.GroupToSingleDocument != null)
                    hashCode = hashCode * 59 + this.GroupToSingleDocument.GetHashCode();
                if (this.AskQuestionsFirst != null)
                    hashCode = hashCode * 59 + this.AskQuestionsFirst.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
