/* 
 * Xpertdoc SmartFlows
 *
 * This describes the REST api for one Xpertdoc SmartFlows project
 *
 * OpenAPI spec version: 4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xpertdoc.SmartFlows.Client.Api;
using Xpertdoc.SmartFlows.Client.Model;
using Xpertdoc.SmartFlows.Client.Client;
using System.Reflection;

namespace Xpertdoc.SmartFlows.Client.Test
{
    /// <summary>
    ///  Class for testing DatasetContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DatasetContentTests
    {
        // TODO uncomment below to declare an instance variable for DatasetContent
        //private DatasetContent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DatasetContent
            //instance = new DatasetContent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DatasetContent
        /// </summary>
        [Test]
        public void DatasetContentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DatasetContent
            //Assert.IsInstanceOfType<DatasetContent> (instance, "variable 'instance' is a DatasetContent");
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'StandardContent'
        /// </summary>
        [Test]
        public void StandardContentTest()
        {
            // TODO unit test for the property 'StandardContent'
        }
        /// <summary>
        /// Test the property 'CustomContent'
        /// </summary>
        [Test]
        public void CustomContentTest()
        {
            // TODO unit test for the property 'CustomContent'
        }
        /// <summary>
        /// Test the property 'SchemaContent'
        /// </summary>
        [Test]
        public void SchemaContentTest()
        {
            // TODO unit test for the property 'SchemaContent'
        }
        /// <summary>
        /// Test the property 'ExtendedContent'
        /// </summary>
        [Test]
        public void ExtendedContentTest()
        {
            // TODO unit test for the property 'ExtendedContent'
        }

    }

}
