/* 
 * Xpertdoc SmartFlows
 *
 * This describes the REST api for one Xpertdoc SmartFlows project
 *
 * OpenAPI spec version: 4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xpertdoc.SmartFlows.Client.Api;
using Xpertdoc.SmartFlows.Client.Model;
using Xpertdoc.SmartFlows.Client.Client;
using System.Reflection;

namespace Xpertdoc.SmartFlows.Client.Test
{
    /// <summary>
    ///  Class for testing EntityField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EntityFieldTests
    {
        // TODO uncomment below to declare an instance variable for EntityField
        //private EntityField instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EntityField
            //instance = new EntityField();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EntityField
        /// </summary>
        [Test]
        public void EntityFieldInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EntityField
            //Assert.IsInstanceOfType<EntityField> (instance, "variable 'instance' is a EntityField");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Test]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Test]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }
        /// <summary>
        /// Test the property 'Advanced'
        /// </summary>
        [Test]
        public void AdvancedTest()
        {
            // TODO unit test for the property 'Advanced'
        }

    }

}
