/* 
 * Xpertdoc SmartFlows
 *
 * This describes the REST api for one Xpertdoc SmartFlows project
 *
 * OpenAPI spec version: 4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xpertdoc.SmartFlows.Client.Api;
using Xpertdoc.SmartFlows.Client.Model;
using Xpertdoc.SmartFlows.Client.Client;
using System.Reflection;

namespace Xpertdoc.SmartFlows.Client.Test
{
    /// <summary>
    ///  Class for testing FilterCondition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FilterConditionTests
    {
        // TODO uncomment below to declare an instance variable for FilterCondition
        //private FilterCondition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FilterCondition
            //instance = new FilterCondition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FilterCondition
        /// </summary>
        [Test]
        public void FilterConditionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FilterCondition
            //Assert.IsInstanceOfType<FilterCondition> (instance, "variable 'instance' is a FilterCondition");
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property '_Operator'
        /// </summary>
        [Test]
        public void _OperatorTest()
        {
            // TODO unit test for the property '_Operator'
        }
        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Test]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }

    }

}
