/* 
 * Xpertdoc SmartFlows
 *
 * This describes the REST api for one Xpertdoc SmartFlows project
 *
 * OpenAPI spec version: 4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xpertdoc.SmartFlows.Client.Api;
using Xpertdoc.SmartFlows.Client.Model;
using Xpertdoc.SmartFlows.Client.Client;
using System.Reflection;

namespace Xpertdoc.SmartFlows.Client.Test
{
    /// <summary>
    ///  Class for testing FlowStep
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlowStepTests
    {
        // TODO uncomment below to declare an instance variable for FlowStep
        //private FlowStep instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlowStep
            //instance = new FlowStep();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlowStep
        /// </summary>
        [Test]
        public void FlowStepInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlowStep
            //Assert.IsInstanceOfType<FlowStep> (instance, "variable 'instance' is a FlowStep");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Test]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'IconClass'
        /// </summary>
        [Test]
        public void IconClassTest()
        {
            // TODO unit test for the property 'IconClass'
        }
        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Test]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'PrimaryParameters'
        /// </summary>
        [Test]
        public void PrimaryParametersTest()
        {
            // TODO unit test for the property 'PrimaryParameters'
        }
        /// <summary>
        /// Test the property 'InputSchema'
        /// </summary>
        [Test]
        public void InputSchemaTest()
        {
            // TODO unit test for the property 'InputSchema'
        }
        /// <summary>
        /// Test the property 'InputForm'
        /// </summary>
        [Test]
        public void InputFormTest()
        {
            // TODO unit test for the property 'InputForm'
        }
        /// <summary>
        /// Test the property 'OutputId'
        /// </summary>
        [Test]
        public void OutputIdTest()
        {
            // TODO unit test for the property 'OutputId'
        }
        /// <summary>
        /// Test the property 'ExternalOutputParameters'
        /// </summary>
        [Test]
        public void ExternalOutputParametersTest()
        {
            // TODO unit test for the property 'ExternalOutputParameters'
        }
        /// <summary>
        /// Test the property 'OutputSchema'
        /// </summary>
        [Test]
        public void OutputSchemaTest()
        {
            // TODO unit test for the property 'OutputSchema'
        }

    }

}
