/* 
 * Xpertdoc SmartFlows
 *
 * This describes the REST api for one Xpertdoc SmartFlows project
 *
 * OpenAPI spec version: 4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xpertdoc.SmartFlows.Client.Api;
using Xpertdoc.SmartFlows.Client.Model;
using Xpertdoc.SmartFlows.Client.Client;
using System.Reflection;

namespace Xpertdoc.SmartFlows.Client.Test
{
    /// <summary>
    ///  Class for testing MultiDependencyMapping
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MultiDependencyMappingTests
    {
        // TODO uncomment below to declare an instance variable for MultiDependencyMapping
        //private MultiDependencyMapping instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MultiDependencyMapping
            //instance = new MultiDependencyMapping();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MultiDependencyMapping
        /// </summary>
        [Test]
        public void MultiDependencyMappingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MultiDependencyMapping
            //Assert.IsInstanceOfType<MultiDependencyMapping> (instance, "variable 'instance' is a MultiDependencyMapping");
        }

        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'Targets'
        /// </summary>
        [Test]
        public void TargetsTest()
        {
            // TODO unit test for the property 'Targets'
        }

    }

}
