/* 
 * Xpertdoc SmartFlows
 *
 * This describes the REST api for one Xpertdoc SmartFlows project
 *
 * OpenAPI spec version: 4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xpertdoc.SmartFlows.Client.Api;
using Xpertdoc.SmartFlows.Client.Model;
using Xpertdoc.SmartFlows.Client.Client;
using System.Reflection;

namespace Xpertdoc.SmartFlows.Client.Test
{
    /// <summary>
    ///  Class for testing ObjectUsage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ObjectUsageTests
    {
        // TODO uncomment below to declare an instance variable for ObjectUsage
        //private ObjectUsage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ObjectUsage
            //instance = new ObjectUsage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ObjectUsage
        /// </summary>
        [Test]
        public void ObjectUsageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ObjectUsage
            //Assert.IsInstanceOfType<ObjectUsage> (instance, "variable 'instance' is a ObjectUsage");
        }


    }

}
