/* 
 * Xpertdoc SmartFlows
 *
 * This describes the REST api for one Xpertdoc SmartFlows project
 *
 * OpenAPI spec version: 4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xpertdoc.SmartFlows.Client.Api;
using Xpertdoc.SmartFlows.Client.Model;
using Xpertdoc.SmartFlows.Client.Client;
using System.Reflection;

namespace Xpertdoc.SmartFlows.Client.Test
{
    /// <summary>
    ///  Class for testing Part
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PartTests
    {
        // TODO uncomment below to declare an instance variable for Part
        //private Part instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Part
            //instance = new Part();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Part
        /// </summary>
        [Test]
        public void PartInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Part
            //Assert.IsInstanceOfType<Part> (instance, "variable 'instance' is a Part");
        }

        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Test]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }
        /// <summary>
        /// Test the property 'TemplateDisplayName'
        /// </summary>
        [Test]
        public void TemplateDisplayNameTest()
        {
            // TODO unit test for the property 'TemplateDisplayName'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property '_Break'
        /// </summary>
        [Test]
        public void _BreakTest()
        {
            // TODO unit test for the property '_Break'
        }
        /// <summary>
        /// Test the property 'LinkHeaders'
        /// </summary>
        [Test]
        public void LinkHeadersTest()
        {
            // TODO unit test for the property 'LinkHeaders'
        }
        /// <summary>
        /// Test the property 'Occurrence'
        /// </summary>
        [Test]
        public void OccurrenceTest()
        {
            // TODO unit test for the property 'Occurrence'
        }
        /// <summary>
        /// Test the property 'Conditions'
        /// </summary>
        [Test]
        public void ConditionsTest()
        {
            // TODO unit test for the property 'Conditions'
        }

    }

}
