/* 
 * SmartFlows
 *
 * This describes the REST api for one SmartFlows project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace Xpertdoc.SmartFlows.Test
{
    /// <summary>
    ///  Class for testing ArchivableItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ArchivableItemTests
    {
        // TODO uncomment below to declare an instance variable for ArchivableItem
        //private ArchivableItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ArchivableItem
            //instance = new ArchivableItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ArchivableItem
        /// </summary>
        [Test]
        public void ArchivableItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ArchivableItem
            //Assert.IsInstanceOfType<ArchivableItem> (instance, "variable 'instance' is a ArchivableItem");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'BinaryContent'
        /// </summary>
        [Test]
        public void BinaryContentTest()
        {
            // TODO unit test for the property 'BinaryContent'
        }

    }

}
