/* 
 * SmartFlows
 *
 * This describes the REST api for one SmartFlows project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace Xpertdoc.SmartFlows.Test
{
    /// <summary>
    ///  Class for testing ConditionGroup
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConditionGroupTests
    {
        // TODO uncomment below to declare an instance variable for ConditionGroup
        //private ConditionGroup instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConditionGroup
            //instance = new ConditionGroup();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConditionGroup
        /// </summary>
        [Test]
        public void ConditionGroupInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConditionGroup
            //Assert.IsInstanceOfType<ConditionGroup> (instance, "variable 'instance' is a ConditionGroup");
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Nodes'
        /// </summary>
        [Test]
        public void NodesTest()
        {
            // TODO unit test for the property 'Nodes'
        }

    }

}
