/* 
 * SmartFlows
 *
 * This describes the REST api for one SmartFlows project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xpertdoc.SmartFlows.Api;
using Xpertdoc.SmartFlows.Model;
using Xpertdoc.SmartFlows.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xpertdoc.SmartFlows.Test
{
    /// <summary>
    ///  Class for testing ConditionOccurrence
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConditionOccurrenceTests
    {
        // TODO uncomment below to declare an instance variable for ConditionOccurrence
        //private ConditionOccurrence instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConditionOccurrence
            //instance = new ConditionOccurrence();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConditionOccurrence
        /// </summary>
        [Test]
        public void ConditionOccurrenceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConditionOccurrence
            //Assert.IsInstanceOfType<ConditionOccurrence> (instance, "variable 'instance' is a ConditionOccurrence");
        }


        /// <summary>
        /// Test the property 'EmptyElementsAreNoneExistant'
        /// </summary>
        [Test]
        public void EmptyElementsAreNoneExistantTest()
        {
            // TODO unit test for the property 'EmptyElementsAreNoneExistant'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'OccurrenceCount'
        /// </summary>
        [Test]
        public void OccurrenceCountTest()
        {
            // TODO unit test for the property 'OccurrenceCount'
        }

    }

}
