/* 
 * SmartFlows
 *
 * This describes the REST api for one SmartFlows project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace Xpertdoc.SmartFlows.Test
{
    /// <summary>
    ///  Class for testing ConditionFlowVariable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConditionFlowVariableTests
    {
        // TODO uncomment below to declare an instance variable for ConditionFlowVariable
        //private ConditionFlowVariable instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConditionFlowVariable
            //instance = new ConditionFlowVariable();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConditionFlowVariable
        /// </summary>
        [Test]
        public void ConditionFlowVariableInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConditionFlowVariable
            //Assert.IsInstanceOfType<ConditionFlowVariable> (instance, "variable 'instance' is a ConditionFlowVariable");
        }


        /// <summary>
        /// Test the property 'BlockId'
        /// </summary>
        [Test]
        public void BlockIdTest()
        {
            // TODO unit test for the property 'BlockId'
        }
        /// <summary>
        /// Test the property 'OutputId'
        /// </summary>
        [Test]
        public void OutputIdTest()
        {
            // TODO unit test for the property 'OutputId'
        }
        /// <summary>
        /// Test the property '_Parameter'
        /// </summary>
        [Test]
        public void _ParameterTest()
        {
            // TODO unit test for the property '_Parameter'
        }
        /// <summary>
        /// Test the property 'DataPath'
        /// </summary>
        [Test]
        public void DataPathTest()
        {
            // TODO unit test for the property 'DataPath'
        }

    }

}
