/* 
 * SmartFlows
 *
 * This describes the REST api for one SmartFlows project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace Xpertdoc.SmartFlows.Test
{
    /// <summary>
    ///  Class for testing CustomContentFieldDateTimeDefault
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CustomContentFieldDateTimeDefaultTests
    {
        // TODO uncomment below to declare an instance variable for CustomContentFieldDateTimeDefault
        //private CustomContentFieldDateTimeDefault instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomContentFieldDateTimeDefault
            //instance = new CustomContentFieldDateTimeDefault();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomContentFieldDateTimeDefault
        /// </summary>
        [Test]
        public void CustomContentFieldDateTimeDefaultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CustomContentFieldDateTimeDefault
            //Assert.IsInstanceOfType<CustomContentFieldDateTimeDefault> (instance, "variable 'instance' is a CustomContentFieldDateTimeDefault");
        }

        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }

    }

}
