/* 
 * SmartFlows
 *
 * This describes the REST api for one SmartFlows project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace Xpertdoc.SmartFlows.Test
{
    /// <summary>
    ///  Class for testing ExpressionFunction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExpressionFunctionTests
    {
        // TODO uncomment below to declare an instance variable for ExpressionFunction
        //private ExpressionFunction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExpressionFunction
            //instance = new ExpressionFunction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExpressionFunction
        /// </summary>
        [Test]
        public void ExpressionFunctionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExpressionFunction
            //Assert.IsInstanceOfType<ExpressionFunction> (instance, "variable 'instance' is a ExpressionFunction");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'HelpLink'
        /// </summary>
        [Test]
        public void HelpLinkTest()
        {
            // TODO unit test for the property 'HelpLink'
        }
        /// <summary>
        /// Test the property 'Categories'
        /// </summary>
        [Test]
        public void CategoriesTest()
        {
            // TODO unit test for the property 'Categories'
        }
        /// <summary>
        /// Test the property 'Varargs'
        /// </summary>
        [Test]
        public void VarargsTest()
        {
            // TODO unit test for the property 'Varargs'
        }
        /// <summary>
        /// Test the property 'Arguments'
        /// </summary>
        [Test]
        public void ArgumentsTest()
        {
            // TODO unit test for the property 'Arguments'
        }

    }

}
