/* 
 * SmartFlows
 *
 * This describes the REST api for one SmartFlows project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace Xpertdoc.SmartFlows.Test
{
    /// <summary>
    ///  Class for testing FlowExecutionOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlowExecutionOutputTests
    {
        // TODO uncomment below to declare an instance variable for FlowExecutionOutput
        //private FlowExecutionOutput instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlowExecutionOutput
            //instance = new FlowExecutionOutput();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlowExecutionOutput
        /// </summary>
        [Test]
        public void FlowExecutionOutputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlowExecutionOutput
            //Assert.IsInstanceOfType<FlowExecutionOutput> (instance, "variable 'instance' is a FlowExecutionOutput");
        }

        /// <summary>
        /// Test the property 'Output'
        /// </summary>
        [Test]
        public void OutputTest()
        {
            // TODO unit test for the property 'Output'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

    }

}
