/* 
 * SmartFlows
 *
 * This describes the REST api for one SmartFlows project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace Xpertdoc.SmartFlows.Test
{
    /// <summary>
    ///  Class for testing FlowOutput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlowOutputTests
    {
        // TODO uncomment below to declare an instance variable for FlowOutput
        //private FlowOutput instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlowOutput
            //instance = new FlowOutput();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlowOutput
        /// </summary>
        [Test]
        public void FlowOutputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlowOutput
            //Assert.IsInstanceOfType<FlowOutput> (instance, "variable 'instance' is a FlowOutput");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Test]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Dataset'
        /// </summary>
        [Test]
        public void DatasetTest()
        {
            // TODO unit test for the property 'Dataset'
        }
        /// <summary>
        /// Test the property 'FieldMap'
        /// </summary>
        [Test]
        public void FieldMapTest()
        {
            // TODO unit test for the property 'FieldMap'
        }

    }

}
