/* 
 * SmartFlows
 *
 * This describes the REST api for one SmartFlows project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xpertdoc.SmartFlows.Api;
using Xpertdoc.SmartFlows.Model;
using Xpertdoc.SmartFlows.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xpertdoc.SmartFlows.Test
{
    /// <summary>
    ///  Class for testing GcpVendorCapabilitySelect
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GcpVendorCapabilitySelectTests
    {
        // TODO uncomment below to declare an instance variable for GcpVendorCapabilitySelect
        //private GcpVendorCapabilitySelect instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GcpVendorCapabilitySelect
            //instance = new GcpVendorCapabilitySelect();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GcpVendorCapabilitySelect
        /// </summary>
        [Test]
        public void GcpVendorCapabilitySelectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GcpVendorCapabilitySelect
            //Assert.IsInstanceOfType<GcpVendorCapabilitySelect> (instance, "variable 'instance' is a GcpVendorCapabilitySelect");
        }


        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Test]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'IsDefault'
        /// </summary>
        [Test]
        public void IsDefaultTest()
        {
            // TODO unit test for the property 'IsDefault'
        }

    }

}
