/* 
 * SmartFlows
 *
 * This describes the REST api for one SmartFlows project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace Xpertdoc.SmartFlows.Test
{
    /// <summary>
    ///  Class for testing PublicSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PublicSettingsTests
    {
        // TODO uncomment below to declare an instance variable for PublicSettings
        //private PublicSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PublicSettings
            //instance = new PublicSettings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PublicSettings
        /// </summary>
        [Test]
        public void PublicSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PublicSettings
            //Assert.IsInstanceOfType<PublicSettings> (instance, "variable 'instance' is a PublicSettings");
        }

        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Test]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }
        /// <summary>
        /// Test the property 'SystemLanguage'
        /// </summary>
        [Test]
        public void SystemLanguageTest()
        {
            // TODO unit test for the property 'SystemLanguage'
        }
        /// <summary>
        /// Test the property 'ProjectConsoleUrl'
        /// </summary>
        [Test]
        public void ProjectConsoleUrlTest()
        {
            // TODO unit test for the property 'ProjectConsoleUrl'
        }
        /// <summary>
        /// Test the property 'FlowExecutionPanelUrl'
        /// </summary>
        [Test]
        public void FlowExecutionPanelUrlTest()
        {
            // TODO unit test for the property 'FlowExecutionPanelUrl'
        }

    }

}
