/* 
 * SmartFlows
 *
 * This describes the REST api for one SmartFlows project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Xpertdoc.SmartFlows.Api;
using Xpertdoc.SmartFlows.Model;
using Xpertdoc.SmartFlows.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Xpertdoc.SmartFlows.Test
{
    /// <summary>
    ///  Class for testing StatisticsPerUser
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StatisticsPerUserTests
    {
        // TODO uncomment below to declare an instance variable for StatisticsPerUser
        //private StatisticsPerUser instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StatisticsPerUser
            //instance = new StatisticsPerUser();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StatisticsPerUser
        /// </summary>
        [Test]
        public void StatisticsPerUserInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StatisticsPerUser
            //Assert.IsInstanceOfType<StatisticsPerUser> (instance, "variable 'instance' is a StatisticsPerUser");
        }


        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Test]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Test]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'Percentage'
        /// </summary>
        [Test]
        public void PercentageTest()
        {
            // TODO unit test for the property 'Percentage'
        }

    }

}
