/* 
 * SmartFlows
 *
 * This describes the REST api for one SmartFlows project 
 *
 * OpenAPI spec version: 4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace Xpertdoc.SmartFlows.Test
{
    /// <summary>
    ///  Class for testing TemplatePortalContentTemplates
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TemplatePortalContentTemplatesTests
    {
        // TODO uncomment below to declare an instance variable for TemplatePortalContentTemplates
        //private TemplatePortalContentTemplates instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TemplatePortalContentTemplates
            //instance = new TemplatePortalContentTemplates();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TemplatePortalContentTemplates
        /// </summary>
        [Test]
        public void TemplatePortalContentTemplatesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TemplatePortalContentTemplates
            //Assert.IsInstanceOfType<TemplatePortalContentTemplates> (instance, "variable 'instance' is a TemplatePortalContentTemplates");
        }

        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'Library'
        /// </summary>
        [Test]
        public void LibraryTest()
        {
            // TODO unit test for the property 'Library'
        }
        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Test]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }
        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Test]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }

    }

}
